spring.application.name=donaton-bff
server.port=8085

services.donaciones.url=http://donaciones-service/api/v1/donaciones
services.necesidades.url=http://necesidades-service/api/v1/necesidades
services.logistica.url=http://logistica-service/api/v1/logistica

spring.web.client.connect-timeout=5000
spring.web.client.read-timeout=10000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
